Repository hjuhalc/haltion, pull requests merged in 2023-02, with the labels that each got.

#4 Properly map redis nil response to http 404
  src/services/otps.rs
Labels: bug, enhancement

#5 Fix unexpected runtime errors
  README.md
  src/services/otps.rs
  src/utils/redis.rs
  src/utils/topt.rs
Labels: bug

#7 Impl. client auth with JWT
  .env.example
  docs/README.md
  docs/haltion-jwt-flow.png
  docs/haltion-otp-flow.png
  src/app.rs
  src/config/env.rs
  src/routes/jwts.rs
  src/routes/mod.rs
  src/routes/otps.rs
  src/services/otps.rs
  src/utils/jwt.rs
Labels: enhancement

#8 Prep pre-requisites for client request authorization
  README.md
  docs/README.md
  docs/auth/README.md
  docs/auth/haltion-jwt-flow.png
  docs/auth/haltion-req-3rd-party.png
  docs/auth/haltion-req-gateway.png
  docs/otp/README.md
  docs/otp/haltion-otp-flow.png
  migration/src/lib.rs
  migration/src/m20230225_062319_create_users_table.rs
  migration/src/m20230225_062404_create_access_groups_table.rs
  migration/src/m20230225_062412_create_permissions_table.rs
  migration/src/m20230225_064453_create_user_groups_table.rs
  migration/src/m20230225_064502_create_group_permissions_table.rs
  src/models/access_groups.rs
  src/models/group_permissions.rs
  src/models/mod.rs
  src/models/otps.rs
  src/models/permissions.rs
  src/models/prelude.rs
  src/models/user_groups.rs
  src/models/users.rs
  src/utils/jwt.rs
Labels: enhancement
